// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:6a50f0c6-255e-4659-a8fb-471ac97ae6e9",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_NWX3LEgG8",
    "aws_user_pools_web_client_id": "4a7jtpkfhci642dr8a0i6152l8"
};


export default awsmobile;
